-- COSMOS PostgreSQL 초기 스키마
-- 공유 또는 배포 이후에는 이 파일을 수정하지 않고 새 버전의 마이그레이션을 추가한다.

-- 사용자
-- 비밀번호에는 평문이 아닌 BCrypt 또는 Argon2 해시를 저장한다.
-- 회원 탈퇴는 deleted_at을 사용하는 soft delete 방식이며 Refresh Token은 Redis에서 관리한다.
CREATE TABLE users (
    user_id            BIGSERIAL PRIMARY KEY,
    email              VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    nickname           VARCHAR(30) NOT NULL,
    role               VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER',
    email_verified_at  TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT chk_users_role CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

-- 산업·데이터 출처·관계 유형 기준 정보
CREATE TABLE industry (
    industry_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_industry_id  UUID,
    name                VARCHAR(100) NOT NULL,
    description         TEXT,
    CONSTRAINT uk_industry_name UNIQUE (name),
    CONSTRAINT fk_industry_parent
        FOREIGN KEY (parent_industry_id) REFERENCES industry (industry_id),
    CONSTRAINT chk_industry_not_self_parent
        CHECK (parent_industry_id IS NULL OR parent_industry_id <> industry_id)
);

CREATE TABLE data_source (
    source_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name         VARCHAR(100) NOT NULL,
    source_type  VARCHAR(50) NOT NULL,
    base_url     TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_data_source_name UNIQUE (name)
);

CREATE TABLE relationship_type (
    relationship_type_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(50) NOT NULL,
    name                  VARCHAR(100) NOT NULL,
    directionality        VARCHAR(20) NOT NULL,
    CONSTRAINT uk_relationship_type_code UNIQUE (code),
    CONSTRAINT chk_relationship_type_directionality
        CHECK (directionality IN ('DIRECTED', 'UNDIRECTED'))
);

-- 수집 실행 및 재시작 위치
CREATE TABLE collection_run (
    run_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    collector_type     VARCHAR(50) NOT NULL,
    source             VARCHAR(100) NOT NULL,
    query              VARCHAR(255),
    status             VARCHAR(30) NOT NULL,
    discovered_count   INTEGER NOT NULL DEFAULT 0,
    success_count      INTEGER NOT NULL DEFAULT 0,
    duplicate_count    INTEGER NOT NULL DEFAULT 0,
    failure_count      INTEGER NOT NULL DEFAULT 0,
    started_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at        TIMESTAMPTZ,
    CONSTRAINT chk_collection_run_counts
        CHECK (
            discovered_count >= 0
            AND success_count >= 0
            AND duplicate_count >= 0
            AND failure_count >= 0
        ),
    CONSTRAINT chk_collection_run_period
        CHECK (finished_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE collection_checkpoint (
    checkpoint_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    collector_id       VARCHAR(100) NOT NULL,
    source             VARCHAR(100) NOT NULL,
    query              VARCHAR(255) NOT NULL DEFAULT '',
    last_cursor        TEXT,
    last_published_at  TIMESTAMPTZ,
    last_success_at    TIMESTAMPTZ,
    CONSTRAINT uk_collection_checkpoint
        UNIQUE (collector_id, source, query)
);

-- 기업 기준 정보
CREATE TABLE company (
    company_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name         VARCHAR(200) NOT NULL,
    name_en      VARCHAR(200),
    stock_code   VARCHAR(30),
    market       VARCHAR(30),
    description  TEXT,
    status       VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_company_market_stock_code UNIQUE (market, stock_code)
);

CREATE TABLE company_alias (
    alias_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id       UUID NOT NULL,
    alias_name       VARCHAR(200) NOT NULL,
    alias_type       VARCHAR(50) NOT NULL,
    normalized_name  VARCHAR(200) NOT NULL,
    CONSTRAINT fk_company_alias_company
        FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE,
    CONSTRAINT uk_company_alias_normalized
        UNIQUE (company_id, normalized_name, alias_type)
);

CREATE TABLE company_industry (
    company_id   UUID NOT NULL,
    industry_id  UUID NOT NULL,
    is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (company_id, industry_id),
    CONSTRAINT fk_company_industry_company
        FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_industry_industry
        FOREIGN KEY (industry_id) REFERENCES industry (industry_id)
);

-- 뉴스·공시 공통 문서와 유형별 상세 정보
CREATE TABLE source_document (
    document_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id           UUID NOT NULL,
    document_type       VARCHAR(20) NOT NULL,
    title               TEXT NOT NULL,
    summary             TEXT,
    original_url        TEXT NOT NULL,
    published_at        TIMESTAMPTZ,
    first_collected_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content_hash        CHAR(64),
    hdfs_raw_uri        TEXT,
    hdfs_clean_uri      TEXT,
    status              VARCHAR(30) NOT NULL,
    analysis_version    VARCHAR(50),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source_document_source
        FOREIGN KEY (source_id) REFERENCES data_source (source_id),
    CONSTRAINT chk_source_document_type
        CHECK (document_type IN ('NEWS', 'DISCLOSURE'))
);

CREATE TABLE news_article (
    document_id         UUID PRIMARY KEY,
    publisher           VARCHAR(200),
    canonical_url       TEXT NOT NULL,
    canonical_url_hash  CHAR(64) NOT NULL,
    author              VARCHAR(200),
    CONSTRAINT fk_news_article_document
        FOREIGN KEY (document_id) REFERENCES source_document (document_id) ON DELETE CASCADE,
    CONSTRAINT uk_news_article_canonical_url_hash UNIQUE (canonical_url_hash)
);

CREATE TABLE disclosure (
    document_id        UUID PRIMARY KEY,
    filing_company_id  UUID NOT NULL,
    dart_receipt_no    VARCHAR(30) NOT NULL,
    report_code        VARCHAR(30),
    report_name        VARCHAR(300) NOT NULL,
    filing_date        DATE NOT NULL,
    disclosure_type    VARCHAR(50),
    correction_status  VARCHAR(30),
    CONSTRAINT fk_disclosure_document
        FOREIGN KEY (document_id) REFERENCES source_document (document_id) ON DELETE CASCADE,
    CONSTRAINT fk_disclosure_company
        FOREIGN KEY (filing_company_id) REFERENCES company (company_id),
    CONSTRAINT uk_disclosure_dart_receipt_no UNIQUE (dart_receipt_no)
);

CREATE TABLE news_discovery (
    discovery_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id         UUID NOT NULL,
    collection_run_id   UUID NOT NULL,
    query               VARCHAR(255) NOT NULL DEFAULT '',
    discovery_type      VARCHAR(50) NOT NULL,
    provider            VARCHAR(100) NOT NULL,
    discovered_url      TEXT NOT NULL,
    discovered_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_discovered_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    discovery_count     INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_news_discovery_article
        FOREIGN KEY (document_id) REFERENCES news_article (document_id) ON DELETE CASCADE,
    CONSTRAINT fk_news_discovery_run
        FOREIGN KEY (collection_run_id) REFERENCES collection_run (run_id),
    CONSTRAINT uk_news_discovery_identity
        UNIQUE (document_id, query, discovery_type, provider),
    CONSTRAINT chk_news_discovery_count CHECK (discovery_count > 0),
    CONSTRAINT chk_news_discovery_period
        CHECK (last_discovered_at >= discovered_at)
);

-- 문서에서 추출한 기업·감성·근거
CREATE TABLE company_document (
    document_id         UUID NOT NULL,
    company_id          UUID NOT NULL,
    mention_type        VARCHAR(50),
    relevance_score     NUMERIC(7, 6),
    sentiment           VARCHAR(30),
    impact_score        NUMERIC(7, 6),
    confidence          NUMERIC(7, 6),
    model_version       VARCHAR(50),
    is_service_visible  BOOLEAN NOT NULL DEFAULT TRUE,
    analyzed_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (document_id, company_id),
    CONSTRAINT fk_company_document_document
        FOREIGN KEY (document_id) REFERENCES source_document (document_id) ON DELETE CASCADE,
    CONSTRAINT fk_company_document_company
        FOREIGN KEY (company_id) REFERENCES company (company_id),
    CONSTRAINT chk_company_document_relevance
        CHECK (relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1),
    CONSTRAINT chk_company_document_impact
        CHECK (impact_score IS NULL OR impact_score BETWEEN -1 AND 1),
    CONSTRAINT chk_company_document_confidence
        CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

CREATE TABLE document_evidence (
    evidence_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id     UUID NOT NULL,
    company_id      UUID NOT NULL,
    sentence_text   TEXT NOT NULL,
    sentence_order  INTEGER NOT NULL,
    confidence      NUMERIC(7, 6),
    model_version   VARCHAR(50),
    CONSTRAINT fk_document_evidence_company_document
        FOREIGN KEY (document_id, company_id)
        REFERENCES company_document (document_id, company_id) ON DELETE CASCADE,
    CONSTRAINT uk_document_evidence_document
        UNIQUE (evidence_id, document_id),
    CONSTRAINT chk_document_evidence_order CHECK (sentence_order >= 0),
    CONSTRAINT chk_document_evidence_confidence
        CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

-- 공통 그래프 스냅샷과 기업 관계 점수
CREATE TABLE graph_snapshot (
    snapshot_id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    as_of_at         TIMESTAMPTZ NOT NULL,
    formula_version  VARCHAR(50) NOT NULL,
    model_version    VARCHAR(50) NOT NULL,
    status           VARCHAR(30) NOT NULL,
    hdfs_uri         TEXT,
    published_at     TIMESTAMPTZ,
    CONSTRAINT chk_graph_snapshot_published
        CHECK (
            status <> 'PUBLISHED'
            OR (published_at IS NOT NULL AND hdfs_uri IS NOT NULL)
        )
);

CREATE TABLE company_relationship (
    relationship_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_company_id     UUID NOT NULL,
    target_company_id     UUID NOT NULL,
    relationship_type_id  SMALLINT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_relationship_source
        FOREIGN KEY (source_company_id) REFERENCES company (company_id),
    CONSTRAINT fk_company_relationship_target
        FOREIGN KEY (target_company_id) REFERENCES company (company_id),
    CONSTRAINT fk_company_relationship_type
        FOREIGN KEY (relationship_type_id)
        REFERENCES relationship_type (relationship_type_id),
    CONSTRAINT uk_company_relationship_identity
        UNIQUE (source_company_id, target_company_id, relationship_type_id),
    CONSTRAINT chk_company_relationship_distinct_companies
        CHECK (source_company_id <> target_company_id)
);

CREATE TABLE relationship_score_current (
    relationship_id   UUID NOT NULL,
    window_type       VARCHAR(30) NOT NULL,
    snapshot_id       UUID NOT NULL,
    score             NUMERIC(18, 6) NOT NULL,
    impact_direction  VARCHAR(30),
    confidence        NUMERIC(7, 6),
    evidence_count    INTEGER NOT NULL DEFAULT 0,
    formula_version   VARCHAR(50) NOT NULL,
    as_of_at          TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (relationship_id, window_type),
    CONSTRAINT fk_relationship_score_current_relationship
        FOREIGN KEY (relationship_id)
        REFERENCES company_relationship (relationship_id) ON DELETE CASCADE,
    CONSTRAINT fk_relationship_score_current_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES graph_snapshot (snapshot_id),
    CONSTRAINT chk_relationship_score_current_confidence
        CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT chk_relationship_score_current_evidence_count
        CHECK (evidence_count >= 0)
);

CREATE TABLE relationship_score_history (
    score_history_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relationship_id   UUID NOT NULL,
    snapshot_id       UUID NOT NULL,
    window_type       VARCHAR(30) NOT NULL,
    score             NUMERIC(18, 6) NOT NULL,
    impact_direction  VARCHAR(30),
    confidence        NUMERIC(7, 6),
    period_start      TIMESTAMPTZ NOT NULL,
    period_end        TIMESTAMPTZ NOT NULL,
    formula_version   VARCHAR(50) NOT NULL,
    CONSTRAINT fk_relationship_score_history_relationship
        FOREIGN KEY (relationship_id)
        REFERENCES company_relationship (relationship_id) ON DELETE CASCADE,
    CONSTRAINT fk_relationship_score_history_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES graph_snapshot (snapshot_id),
    CONSTRAINT uk_relationship_score_history
        UNIQUE (relationship_id, snapshot_id, window_type),
    CONSTRAINT chk_relationship_score_history_confidence
        CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT chk_relationship_score_history_period
        CHECK (period_end >= period_start)
);

CREATE TABLE relationship_evidence (
    relationship_evidence_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    relationship_id           UUID NOT NULL,
    document_id               UUID NOT NULL,
    evidence_id               UUID,
    contribution_score        NUMERIC(18, 6),
    model_version             VARCHAR(50),
    formula_version           VARCHAR(50),
    CONSTRAINT fk_relationship_evidence_relationship
        FOREIGN KEY (relationship_id)
        REFERENCES company_relationship (relationship_id) ON DELETE CASCADE,
    CONSTRAINT fk_relationship_evidence_document
        FOREIGN KEY (document_id) REFERENCES source_document (document_id) ON DELETE CASCADE,
    CONSTRAINT fk_relationship_evidence_sentence
        FOREIGN KEY (evidence_id, document_id)
        REFERENCES document_evidence (evidence_id, document_id),
    CONSTRAINT uk_relationship_evidence_identity
        UNIQUE (relationship_id, document_id, evidence_id)
);

-- 기업 지표 및 주가 시계열
CREATE TABLE company_metric_history (
    company_id          UUID NOT NULL,
    measured_at         TIMESTAMPTZ NOT NULL,
    news_mention_count  INTEGER NOT NULL DEFAULT 0,
    positive_count      INTEGER NOT NULL DEFAULT 0,
    negative_count      INTEGER NOT NULL DEFAULT 0,
    sentiment_score     NUMERIC(18, 6),
    relationship_count  INTEGER NOT NULL DEFAULT 0,
    metric_version      VARCHAR(50) NOT NULL,
    PRIMARY KEY (company_id, measured_at),
    CONSTRAINT fk_company_metric_history_company
        FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE,
    CONSTRAINT chk_company_metric_history_counts
        CHECK (
            news_mention_count >= 0
            AND positive_count >= 0
            AND negative_count >= 0
            AND relationship_count >= 0
        )
);

CREATE TABLE stock_price_history (
    company_id      UUID NOT NULL,
    trading_at      TIMESTAMPTZ NOT NULL,
    interval_type   VARCHAR(20) NOT NULL,
    open_price      NUMERIC(20, 4) NOT NULL,
    high_price      NUMERIC(20, 4) NOT NULL,
    low_price       NUMERIC(20, 4) NOT NULL,
    close_price     NUMERIC(20, 4) NOT NULL,
    trading_volume  BIGINT NOT NULL,
    PRIMARY KEY (company_id, trading_at, interval_type),
    CONSTRAINT fk_stock_price_history_company
        FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE,
    CONSTRAINT chk_stock_price_history_prices
        CHECK (
            open_price >= 0
            AND high_price >= 0
            AND low_price >= 0
            AND close_price >= 0
            AND high_price >= low_price
        ),
    CONSTRAINT chk_stock_price_history_volume CHECK (trading_volume >= 0)
);

-- 사용자 서비스 기능
CREATE TABLE company_community_comment (
    comment_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id  UUID NOT NULL,
    user_id     BIGINT NOT NULL,
    content     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_company_community_comment_company
        FOREIGN KEY (company_id) REFERENCES company (company_id),
    CONSTRAINT fk_company_community_comment_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT chk_company_community_comment_content
        CHECK (length(btrim(content)) > 0)
);

CREATE TABLE user_watch_company (
    user_id     BIGINT NOT NULL,
    company_id  UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, company_id),
    CONSTRAINT fk_user_watch_company_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_watch_company_company
        FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE
);

CREATE TABLE user_scrap (
    user_id      BIGINT NOT NULL,
    document_id  UUID NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, document_id),
    CONSTRAINT fk_user_scrap_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_scrap_news
        FOREIGN KEY (document_id) REFERENCES news_article (document_id) ON DELETE CASCADE
);

CREATE TABLE user_weight_setting (
    user_id      BIGINT PRIMARY KEY,
    news_weight  NUMERIC(5, 2) NOT NULL DEFAULT 50.00,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_weight_setting_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT chk_user_weight_setting_news_weight
        CHECK (news_weight BETWEEN 0 AND 100)
);

-- 최종 실패와 HDFS 데이터 묶음 운영 정보
CREATE TABLE failure_record (
    failure_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id             UUID NOT NULL,
    document_id        UUID,
    event_id           VARCHAR(100),
    source             VARCHAR(100) NOT NULL,
    external_id        VARCHAR(200),
    source_url         TEXT,
    stage              VARCHAR(50) NOT NULL,
    error_code         VARCHAR(100),
    error_message      TEXT NOT NULL,
    retry_count        INTEGER NOT NULL DEFAULT 0,
    dlq_topic          VARCHAR(200),
    resolution_status  VARCHAR(30) NOT NULL DEFAULT 'UNRESOLVED',
    occurred_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at        TIMESTAMPTZ,
    CONSTRAINT fk_failure_record_run
        FOREIGN KEY (run_id) REFERENCES collection_run (run_id),
    CONSTRAINT fk_failure_record_document
        FOREIGN KEY (document_id) REFERENCES source_document (document_id),
    CONSTRAINT chk_failure_record_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_failure_record_resolved_at
        CHECK (resolved_at IS NULL OR resolved_at >= occurred_at)
);

CREATE TABLE data_asset (
    asset_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id          UUID NOT NULL,
    dataset_type    VARCHAR(50) NOT NULL,
    hdfs_uri        TEXT NOT NULL,
    schema_version  VARCHAR(50) NOT NULL,
    record_count    BIGINT NOT NULL DEFAULT 0,
    file_size       BIGINT NOT NULL DEFAULT 0,
    checksum        VARCHAR(128),
    status          VARCHAR(30) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_data_asset_run
        FOREIGN KEY (run_id) REFERENCES collection_run (run_id),
    CONSTRAINT chk_data_asset_sizes
        CHECK (record_count >= 0 AND file_size >= 0),
    CONSTRAINT uk_data_asset_hdfs_uri UNIQUE (hdfs_uri)
);

-- 활성 회원의 이메일과 닉네임만 유일하게 유지한다.
CREATE UNIQUE INDEX ux_users_email
    ON users (lower(email))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX ux_users_nickname
    ON users (nickname)
    WHERE deleted_at IS NULL;

-- 기업 검색 및 산업 필터
CREATE INDEX ix_company_name ON company (name);
CREATE INDEX ix_company_stock_code ON company (stock_code);
CREATE INDEX ix_company_alias_normalized_name ON company_alias (normalized_name);
CREATE INDEX ix_company_industry_industry ON company_industry (industry_id, company_id);
CREATE UNIQUE INDEX ux_company_industry_primary
    ON company_industry (company_id)
    WHERE is_primary;

-- 최신 문서와 기업별 관련 문서 조회
CREATE INDEX ix_source_document_type_published
    ON source_document (document_type, published_at DESC);
CREATE INDEX ix_source_document_content_hash ON source_document (content_hash);
CREATE INDEX ix_company_document_company_analyzed
    ON company_document (company_id, analyzed_at DESC);
CREATE INDEX ix_document_evidence_document_company
    ON document_evidence (document_id, company_id);
CREATE INDEX ix_news_discovery_run ON news_discovery (collection_run_id);

-- 그래프와 관계 근거 조회
CREATE INDEX ix_company_relationship_source ON company_relationship (source_company_id);
CREATE INDEX ix_company_relationship_target ON company_relationship (target_company_id);
CREATE INDEX ix_relationship_score_current_snapshot_score
    ON relationship_score_current (snapshot_id, score DESC);
CREATE INDEX ix_relationship_score_history_relationship_period
    ON relationship_score_history (relationship_id, period_end DESC);
CREATE INDEX ix_relationship_evidence_relationship
    ON relationship_evidence (relationship_id);
CREATE INDEX ix_relationship_evidence_document
    ON relationship_evidence (document_id);
CREATE INDEX ix_graph_snapshot_status_as_of
    ON graph_snapshot (status, as_of_at DESC);

-- 서비스 목록 조회
CREATE INDEX ix_company_community_comment_company_created
    ON company_community_comment (company_id, created_at DESC);
CREATE INDEX ix_company_community_comment_created
    ON company_community_comment (created_at DESC);
CREATE INDEX ix_user_scrap_user_created ON user_scrap (user_id, created_at DESC);
CREATE INDEX ix_company_metric_history_measured
    ON company_metric_history (measured_at DESC);
CREATE INDEX ix_stock_price_history_company_interval_time
    ON stock_price_history (company_id, interval_type, trading_at DESC);

-- 수집 파이프라인 운영 조회
CREATE INDEX ix_collection_run_started ON collection_run (started_at DESC);
CREATE INDEX ix_failure_record_run_occurred
    ON failure_record (run_id, occurred_at DESC);
CREATE INDEX ix_failure_record_resolution_occurred
    ON failure_record (resolution_status, occurred_at DESC);
CREATE INDEX ix_data_asset_run ON data_asset (run_id);
